#!/usr/bin/env perl
use strict;
use warnings;

use lib qw(/home/gene/repos/CORION/random-poissondisc/lib);
use Random::PoissonDisc ();
use SVG qw(title);

my $items = shift || 500;
my $size  = shift || 500;

my $fill   = 'white';
my $border = 'black';

my $svg = SVG->new(
    width  => $size,
    height => $size,
);
$svg->title()->cdata('Poisson Distribution');

my $style = $svg->group(
    id    => 'style-group',
    style => {
        stroke => $border,
        fill   => $fill,
    },
);

# Inversely proportional to the number of points needed
my $delta = 10;
# 2400->8, 1900->9, 1500->10

my $points = Random::PoissonDisc->points(
    dimensions => [$size, $size],
    r          => $delta,
    avoid_edge => $delta,
);

my $i = 0;

for my $point ($points->@*) {
    $i++;

    $style->anchor(
        id     => $i . '-anchor',
        -href  => 'https://ology.github.io/',
        target => '_blank'
    )->circle(
        cx => $point->[0],
        cy => $point->[1],
        r  => 3,
        id => $i . '-point'
    );
}
warn __PACKAGE__,' L',__LINE__,' ',,"$i\n";

print $svg->xmlify;
