#!/usr/bin/env perl
use strict;
use warnings;

use Math::Trig qw(pi cot);
use SVG qw(title);

#use Math::Spiral;
#my $spiral = Math::Spiral->new;
#    my ($x, $y) = $spiral->Next;

my $A    = shift // 1;
my $B    = shift // 1.5;
my $max  = shift || 20;
my $size = shift || 400;
my $incr = shift || 0.05;
my $fill = shift || 'white';
my $line = shift || 'black';

my $svg = SVG->new(
    width  => $size,
    height => $size,
);
$svg->title()->cdata('Spiral');

my $style = $svg->group(
    id    => 'style-group',
    style => {
        stroke => $line,
        fill   => $fill,
    },
);

my %seen;

for (my $theta = 0; $theta < $max * pi; $theta += $incr) {
    my $rho = $A + $B * $theta; # Archimedean
#    my $rho = $A * exp($theta * cot($B)); # Logarithmic

    my $x = $size / 2 + $rho * cos($theta / pi);
    my $y = $size / 2 + $rho * sin($theta / pi);

    my $id = $x . '_' . $y . '-point';

    $style->circle(
        id => $id,
        cx => $x,
        cy => $y,
        r  => 1,
    );
}

print $svg->xmlify;
